services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      

networks:
  db_net:
    external: true
